name: mysimenv
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=py313haa95532_0
  - brotli-python=1.0.9=py313h5da7b33_9
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.9.9=haa95532_0
  - colorama=0.4.6=py313haa95532_0
  - comm=0.2.1=py313haa95532_0
  - cpuonly=2.0=0
  - cuda-cccl=13.0.85=h5221881_1
  - cuda-cccl_win-64=13.0.85=hc667259_1
  - cuda-cudart=12.4.127=0
  - cuda-cudart-dev=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-libraries-dev=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvrtc-dev=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=13.0.85=h17533db_0
  - cuda-opencl-dev=13.0.85=hde976d8_0
  - cuda-profiler-api=13.0.85=h5221881_0
  - cuda-runtime=12.4.1=0
  - cuda-version=13.0=3
  - debugpy=1.8.11=py313h5da7b33_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - freetype=2.13.3=h57928b3_1
  - glib=2.84.2=he8f994d_0
  - glib-tools=2.84.2=h4394cf3_0
  - gst-plugins-base=1.24.11=h3fe0a9e_0
  - gstreamer=1.24.11=h233a61a_0
  - icu=75.1=he0c23c2_0
  - intel-openmp=2024.2.1=h57928b3_1083
  - ipykernel=6.29.5=py313haa95532_1
  - ipython=9.1.0=py313haa95532_0
  - ipython_pygments_lexers=1.1.1=py313haa95532_0
  - jedi=0.19.2=py313haa95532_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jupyter_client=8.6.3=py313haa95532_0
  - jupyter_core=5.7.2=py313haa95532_0
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - kiwisolver=1.4.8=py313h5da7b33_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h5da7b33_0
  - libabseil=20250127.1=cxx17_h4eb7d71_0
  - libblas=3.9.0=28_h576b46c_mkl
  - libcblas=3.9.0=28_h7ad3364_mkl
  - libclang13=20.1.7=default_h6e92b77_0
  - libcublas=12.4.5.8=0
  - libcublas-dev=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufft-dev=11.2.1.3=0
  - libcurand=10.4.0.35=h86a452a_1
  - libcurand-dev=10.4.0.35=hde976d8_1
  - libcusolver=11.6.1.9=0
  - libcusolver-dev=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libcusparse-dev=12.3.1.170=0
  - libdeflate=1.22=h5bf469e_0
  - libexpat=2.7.0=he0c23c2_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.13.3=h57928b3_1
  - libfreetype6=2.13.3=h0b5ce68_1
  - libgcc=15.1.0=h1383e82_2
  - libglib=2.84.2=hbc94333_0
  - libgomp=15.1.0=h1383e82_2
  - libiconv=1.18=h135ad9c_1
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=3.0.3=h827c3e9_0
  - liblapack=3.9.0=28_hacfb0e4_mkl
  - liblzma=5.8.1=h2466b09_0
  - libmpdec=4.0.0=h827c3e9_0
  - libnpp=12.2.5.30=0
  - libnpp-dev=12.2.5.30=0
  - libnvfatbin=13.0.85=h17533db_0
  - libnvfatbin-dev=13.0.85=h17533db_0
  - libnvjitlink=12.4.127=0
  - libnvjitlink-dev=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libnvjpeg-dev=12.3.1.117=0
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.49=h7a4582a_0
  - libprotobuf=5.29.3=he9d8c4a_1
  - libsodium=1.0.18=h62dcd97_0
  - libsqlite=3.49.1=h67fdade_2
  - libtiff=4.7.0=hdefb170_2
  - libtorch=2.7.1=cpu_mkl_h5c26a8c_100
  - libuv=1.51.0=h2466b09_0
  - libvorbis=1.3.7=he774522_0
  - libwebp-base=1.5.0=h3b0e114_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libzlib=1.3.1=h2466b09_2
  - markupsafe=3.0.2=py313hb4c8b1a_1
  - matplotlib=3.10.0=py313haa95532_1
  - matplotlib-base=3.10.0=py313h7aa5d4e_1
  - matplotlib-inline=0.1.6=py313haa95532_0
  - mkl=2024.2.2=h57928b3_15
  - mpmath=1.3.0=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=py313haa95532_0
  - opencl-headers=2025.06.13=he0c23c2_0
  - openjpeg=2.5.3=h4d64b90_0
  - openssl=3.5.0=ha4e3fda_1
  - optree=0.16.0=py313h1ec8472_0
  - packaging=24.2=py313haa95532_0
  - parso=0.8.4=py313haa95532_0
  - pcre2=10.45=h99c9b8b_0
  - pip=25.0=py313haa95532_0
  - platformdirs=4.3.7=py313haa95532_0
  - ply=3.11=py313haa95532_1
  - prompt-toolkit=3.0.43=py313haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py313h827c3e9_1
  - pthread-stubs=0.3=h3c9f919_1
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyh5e4992e_0
  - pygments=2.19.1=py313haa95532_0
  - pyqt=5.15.10=py313h5da7b33_1
  - pyqt5-sip=12.13.0=py313h827c3e9_1
  - python=3.13.3=h261c0b1_101_cp313
  - python-dateutil=2.9.0post0=py313haa95532_2
  - python_abi=3.13=0_cp313
  - pytorch=2.7.1=cpu_mkl_py313_h6c0da28_100
  - pytorch-cuda=12.4=h3fd98bf_7
  - pytorch-mutex=1.0=cpu
  - pywin32=308=py313h5da7b33_0
  - pyzmq=26.2.0=py313h5da7b33_0
  - qt-main=5.15.15=h9151539_3
  - setuptools=75.8.0=py313haa95532_0
  - sip=6.7.12=py313h5da7b33_1
  - six=1.17.0=py313haa95532_0
  - sleef=3.8=h7e360cc_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.13=h5226925_1
  - tornado=6.4.2=py313h827c3e9_0
  - traitlets=5.14.3=py313haa95532_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.20348.0=haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.42.34438=hfd919c2_26
  - vs2015_runtime=14.42.34438=h7142326_26
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.45.1=py313haa95532_0
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - zeromq=4.3.5=hd77b12b_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - absl-py==2.2.2
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - ale-py==0.11.2
      - alembic==1.17.2
      - attrs==25.4.0
      - bleach==6.3.0
      - bokeh==3.8.1
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - cloudpickle==3.1.1
      - colorcet==3.1.0
      - colorlog==6.10.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - farama-notifications==0.0.4
      - filelock==3.18.0
      - fonttools==4.57.0
      - frozenlist==1.8.0
      - fsspec==2025.3.2
      - greenlet==3.2.4
      - grpcio==1.71.0
      - gymnasium==1.1.1
      - hftbacktest==2.4.3
      - holoviews==1.22.0
      - idna==3.11
      - ipywidgets==8.1.8
      - joblib==1.5.1
      - jupyterlab-widgets==3.0.16
      - linkify-it-py==2.0.3
      - llvmlite==0.45.1
      - mako==1.3.10
      - markdown==3.8
      - markdown-it-py==4.0.0
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - multidict==6.7.0
      - narwhals==2.13.0
      - networkx==3.4.2
      - numba==0.62.1
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - optuna==4.6.0
      - pandas==2.2.3
      - panel==1.8.4
      - param==2.3.1
      - patsy==1.0.1
      - pillow==11.2.1
      - polars==1.35.2
      - polars-runtime-32==1.35.2
      - propcache==0.4.1
      - protobuf==6.30.2
      - pygame==2.6.1
      - pyparsing==3.2.3
      - pytz==2025.2
      - pyviz-comms==3.0.6
      - pyyaml==6.0.3
      - requests==2.32.5
      - rich==14.2.0
      - scikit-learn==1.7.0
      - scipy==1.16.0
      - seaborn==0.13.2
      - sortedcontainers==2.4.0
      - sqlalchemy==2.0.44
      - stable-baselines3==2.7.0
      - statsmodels==0.14.5
      - sympy==1.13.3
      - tardis-dev==2.1.2
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - torch==2.7.0
      - tqdm==4.67.1
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - uc-micro-py==1.0.3
      - urllib3==2.5.0
      - webencodings==0.5.1
      - werkzeug==3.1.3
      - wget==3.2
      - widgetsnbextension==4.0.15
      - xyzservices==2025.11.0
      - yarl==1.22.0
prefix: D:\Downloads\Anaconda\envs\mysimenv
